import random #used to generate words randomly
#from PIL import Image
#import appropriate files
from Movies import movies
from hangman_words import words
from hangman_animals import animals

#Asks for User input for whether they want to play Hangman or not
user = input("Would you like to play Hangman?(y/n)\n")

#Takes care of invalid user input; asks user to answer again if input is invalid
while user.lower() not in ['y', 'n', 'yes', 'no']:
    print("\033[0;31m"+ "Error: Invalid input. please try again." + "\033[0m")
    user = input("Would you like to play Hangman? (y/n)\n")

#If user says they don't want to play
if user.lower() in ['n', 'no']:
    print("See you later. Goodbye!\nTerminating program...")

#If they do, the following would run
else:
    print("Welcome to Hangman")
    #User is asked the category of words
    decision = input("\nPlease choose from one of the following categories: \n1. Movies \n2. Words \n3. Animals\n")

    #Takes care of invalid input and prompts user to resubmit input
    while decision not in ['1', '2', '3']:
        print("\033[0;31m" + "Error: Invalid input. please try again." + "\033[0m")
        decision = input("\nPlease choose from one of the following categories: \n1. Movies \n2. Words \n3. Animals\n")

    #The appropriate files are opened depending on user input and generates random words from list
    if decision == '1':
        word_generated = random.choice(movies)
    elif decision == '2':
        word_generated = random.choice(words)
    else:
        word_generated = random.choice(animals)

    #letter variable that will be used to check whether user enters a letter
    letter = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'


    lives = 6  #total number of lives user has
    used_words = "" #This variable will take care of the words that the user enters

#Asks user for guesses only if they have enough lives
    while lives > 0:

         hang_man = [ch if ch in used_words else '_' for ch in
                     word_generated]  # all characters that are not part of word are replaced with '_'
         print("Current word is", ''.join(hang_man))

         guess = input("\nWhat is your guess?\n").capitalize()
         answer = any(ele in guess for ele in word_generated) #checks if guess is in the list generated by word_generated variable
         #In other words, it checks whether the input is the word. If so, break out of loop. We have a winner!
         if answer and len(guess) == len(word_generated):
             break

        #If user enters something that is not a letter
         if guess not in letter and guess != word_generated:
             print("\033[0;31m" +"Invalid input. Try again." + "\033[0m")

        #If the guess is already in the words guessed, it will display error and ask user for input again.
         elif guess in used_words:
            print("You have already guessed this. Try again.")
            print("You have used these letters: " + used_words)  # Displays all guessed letters

         #Otherwise, proceed
         else:
             used_words = used_words + guess +" "
             print("You have used these letters: " + used_words) #Displays all guessed letters


             #if the guess is not one of the words, lose life
             if guess not in word_generated:
                 lives -=1
                 print("\033[0;31m" +"\nLife Lost!" + "\033[0m")

            #If there's no more underscores left, leave loop
             elif '_' not in hang_man:
                 break

                 #displays hangman
             if (lives == 6):
                 print("\t--------" +
                       "\n\t|      |" +
                       "\n\t|" +
                       "\n\t|" +
                       "\n\t|" +
                       "\n\t|" +
                       "\n\t---")
             elif (lives == 5):
                 print("\t--------" +
                       "\n\t|      |" +
                       "\n\t|      O" +
                       "\n\t|" +
                       "\n\t|" +
                       "\n\t|" +
                       "\n\t---")

             elif (lives == 4):
                 print("\t--------" +
                       "\n\t|      |" +
                       "\n\t|      O" +
                       "\n\t|      |" +
                       "\n\t|      |" +
                       "\n\t|" +
                       "\n\t---")
             elif (lives == 3):
                 print("\t--------" +
                       "\n\t|      |" +
                       "\n\t|      O" +
                       "\n\t|     \\|" +
                       "\n\t|      |" +
                       "\n\t|     " +
                       "\n\t---")

             elif (lives == 2):
                 print("\t--------" +
                       "\n\t|      |" +
                       "\n\t|      O" +
                       "\n\t|     \\|/" +
                       "\n\t|      |" +
                       "\n\t|     " +
                       "\n\t---")
             else:
                 print("\t--------" +
                       "\n\t|      |" +
                       "\n\t|      O" +
                       "\n\t|     \\|/" +
                       "\n\t|      |" +
                       "\n\t|     /" +
                       "\n\t---")
             print("You have ", lives, " lives left.")

   #Display message if user lost along with finished hang man
    if lives == 0:
        print("\t--------" +
              "\n\t|      |" +
              "\n\t|      O" +
              "\n\t|     \\|/" +
              "\n\t|      |" +
              "\n\t|     / \\" +
              "\n\t---")
        print("You are out of lives. You Lose! The correct word was: " + word_generated)

    #Display message if user won
    else:
        print("You win! The answer was " + word_generated)
